### ISSUE TITLE
Error on Edits via UI - Cassandra 3.11.1

### ISSUE THREAD

**Issue by rsbrisci** [avalanche123/cassandra-web#11]
while attempting to edit a record via the UI, we saw this error:
Invalid request: Invalid HTTP format, parsing fails.
        /usr/local/rvm/gems/ruby-2.4.1/gems/thin-1.7.2/lib/thin/request.rb:84:in `execute'
        /usr/local/rvm/gems/ruby-2.4.1/gems/thin-1.7.2/lib/thin/request.rb:84:in `parse'
        /usr/local/rvm/gems/ruby-2.4.1/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
        /usr/local/rvm/gems/ruby-2.4.1/gems/eventmachine-1.2.6/lib/eventmachine.rb:195:in `run_machine'
        /usr/local/rvm/gems/ruby-2.4.1/gems/eventmachine-1.2.6/lib/eventmachine.rb:195:in `run'
        /usr/local/rvm/gems/ruby-2.4.1/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
        /usr/local/rvm/gems/ruby-2.4.1/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
        /usr/local/rvm/gems/ruby-2.4.1/gems/thin-1.7.2/lib/thin/server.rb:148:in `start'
        /usr/local/rvm/gems/ruby-2.4.1/gems/cassandra-web-0.4.0/bin/cassandra-web:85:in `run'
        /usr/local/rvm/gems/ruby-2.4.1/gems/cassandra-web-0.4.0/bin/cassandra-web:104:in `<top (required)>'
        /usr/local/rvm/gems/ruby-2.4.1/bin/cassandra-web:23:in `load'
        /usr/local/rvm/gems/ruby-2.4.1/bin/cassandra-web:23:in `<main>'
        /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
        /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by daverogers** [comment]
I had this issue and noticed I was running `https` not `http`
