### ISSUE TITLE
 Cannot start:  cannot load such file -- bundler/setup (LoadError)

### ISSUE THREAD

**Issue by ttpro1995** [avalanche123/cassandra-web#25]
```
(base) ➜  ~ sudo cassandra-web 
Traceback (most recent call last):
	8: from /usr/local/bin/cassandra-web:23:in `<main>'
	7: from /usr/local/bin/cassandra-web:23:in `load'
	6: from /var/lib/gems/2.5.0/gems/cassandra-web-0.5.0/bin/cassandra-web:104:in `<top (required)>'
	5: from /var/lib/gems/2.5.0/gems/cassandra-web-0.5.0/bin/cassandra-web:46:in `run'
	4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	3: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	2: from /var/lib/gems/2.5.0/gems/cassandra-web-0.5.0/app.rb:6:in `<top (required)>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler/setup (LoadError)
(base) ➜  ~ cassandra-web  
Traceback (most recent call last):
	8: from /usr/local/bin/cassandra-web:23:in `<main>'
	7: from /usr/local/bin/cassandra-web:23:in `load'
	6: from /var/lib/gems/2.5.0/gems/cassandra-web-0.5.0/bin/cassandra-web:104:in `<top (required)>'
	5: from /var/lib/gems/2.5.0/gems/cassandra-web-0.5.0/bin/cassandra-web:46:in `run'
	4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	3: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	2: from /var/lib/gems/2.5.0/gems/cassandra-web-0.5.0/app.rb:6:in `<top (required)>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler/setup (LoadError)

```

**Comment by smclinden** [comment]
I'm getting the same error, Ubuntu 18.04 LTS.

Try downloading rvm for your OS version (rvm.io).

Install it, then run "rvm install ruby-2.5.0" and then "rvm use 2.5.0".

You'll, likely, need some additional packages. Try "bundle update <package name>" (in my case, "rake").
