### ISSUE TITLE
issue in cassandra-web command in ubuntu 20

### ISSUE THREAD

**Issue by johnfelipe** [avalanche123/cassandra-web#35]
```
cassandra-web
/usr/local/rvm/gems/ruby-3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:29: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/rvm/gems/ruby-3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/rvm/gems/ruby-3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/rvm/gems/ruby-3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:35: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/rvm/gems/ruby-3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:35: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/rvm/gems/ruby-3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:44: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/rvm/gems/ruby-3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/rvm/gems/ruby-3.0.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:319:in `check_for_activated_spec!': You have already activated ione 1.2.5, but your Gemfile requires ione 1.2.4. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
        from /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:31:in `block in setup'
        from /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/forwardable.rb:238:in `each'
        from /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/forwardable.rb:238:in `each'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:26:in `map'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:26:in `setup'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-1.17.3/lib/bundler.rb:107:in `setup'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-1.17.3/lib/bundler/setup.rb:10:in `<top (required)>'
        from <internal:/usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/cassandra-web-0.5.0/app.rb:6:in `<top (required)>'
        from <internal:/usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/cassandra-web-0.5.0/bin/cassandra-web:46:in `run'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/cassandra-web-0.5.0/bin/cassandra-web:104:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-3.0.0/bin/cassandra-web:23:in `load'
        from /usr/local/rvm/gems/ruby-3.0.0/bin/cassandra-web:23:in `<main>'

```
i have this
```
rvm list
=* ruby-3.0.0 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
```
or tell me wich version i need install for complete task

**Comment by johnfelipe** [comment]
Anyone?
