### ISSUE TITLE
start error after installation

### ISSUE THREAD

**Issue by yongdi** [avalanche123/cassandra-web#6]
my local Cassandra is 3.10.  I have successfully installed it and the first run complains 

> mozats-MacBook-Pro-5:cassandra-web luyu$ cassandra-web  --hosts '127.0.0.1'
> /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
> 	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /usr/local/lib/ruby/gems/2.4.0/gems/cassandra-web-0.4.0/app.rb:6:in `<top (required)>'
> 	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /usr/local/lib/ruby/gems/2.4.0/gems/cassandra-web-0.4.0/bin/cassandra-web:46:in `run'
> 	from /usr/local/lib/ruby/gems/2.4.0/gems/cassandra-web-0.4.0/bin/cassandra-web:104:in `<top (required)>'
> 	from /usr/local/bin/cassandra-web:22:in `load'
> 	from /usr/local/bin/cassandra-web:22:in `<main>'
> 

please help....

**Comment by yongdi** [comment]
I fixed it with:
`gem install bundler`
`bundle install`

**Comment by yongdi** [comment]
I hope you can make a new version to cover this issue

**Comment by xiaoyekanren** [comment]
![aaaaaaa](https://user-images.githubusercontent.com/7812383/38231885-39d142cc-3747-11e8-9369-07cca612ee06.png)

**Comment by jeremyjpj0916** [comment]
@xiaoyekanren that is because you are using IE, try in Firefox it seems to load better in that browser. @yongdi  thanks for this git issue it helped me too :) !
